Metrics/MethodLength:
  Max: 30

Metrics/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 28

AllCops:
  Exclude:
  - db/migrate/*
  - db/schema.rb
  - 'vendor/**/*' # need for travis-ci
    # http://caseywest.com/faster-ci-on-travis-and-docker-for-ruby-and-rails-and-rubocop/
