language: ruby
rvm:
  - "2.2.2"

sudo: false
cache: bundler

before_script: |
  cp config/node_starter.yml.example config/node_starter.yml
  mkdir /tmp/node_bin
  bundle exec rake db:create db:migrate --trace

script:
  - bundle exec rubocop
  - bundle exec rspec
